apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-frontend-deploy
spec:
  podSelector:
    matchLabels:
      app: frontend-deploy
  ingress:
    - from: # 1st egress rule
        - podSelector: # allow egress only to pods with api label
            matchLabels:
              app: busybox