apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      volumes:
        - name: logs
          emptyDir: {}       
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
            - name: logs
              mountPath: /var/log/cleaner
        resources: {}
      - name: logger
        image: busybox:1.31.0
        command: ["sh", "-c", "tail -f /var/log/cleaner/cleaner.log"]
        volumeMounts:
        - name: logs
          mountPath: /var/log/cleaner
status: {}
