apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: secret-db
  containers:
  - image: busybox:1.31.0
    name: pod
    volumeMounts:
    - name: secret-volume
      mountPath: /tmp/secret
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: secret-db
          key: DB_User
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
