apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: job
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: busybox:1.31.0
        name: job
        resources: {}
      restartPolicy: Never
status: {}
