apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
spec:
  containers:
  - command:
    - sh
    - -c
    - sleep 2000
    image: busybox:1.31.0
    name: pod
    resources: {}
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
        exec:
          command:
            - sh 
            - -c 
            - cat /tmp/ready
        initialDelaySeconds: 5 
        periodSeconds: 10
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
